// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import { createEventResponseTransformer, findUserByIdResponseTransformer, getCurrentUserResponseTransformer, getEventByIdResponseTransformer, getEventReservationsResponseTransformer, getEventsResponseTransformer, getMyEventsResponseTransformer, getMyReservationsResponseTransformer, getReservationByIdResponseTransformer, getReservationsResponseTransformer, getUserEventsResponseTransformer, getUserTicketsResponseTransformer, loginResponseTransformer, registerResponseTransformer, reserveEventResponseTransformer, updateEventResponseTransformer, updateReservationResponseTransformer } from './transformers.gen';
import type { CancelReservationData, CancelReservationResponses, CreateEventData, CreateEventResponses, DeleteEventData, DeleteEventResponses, DeleteReservationData, DeleteReservationResponses, FindUserByIdData, FindUserByIdResponses, GetCurrentUserData, GetCurrentUserErrors, GetCurrentUserResponses, GetEventByIdData, GetEventByIdResponses, GetEventReservationsData, GetEventReservationsResponses, GetEventsData, GetEventsResponses, GetMyEventsData, GetMyEventsResponses, GetMyReservationsData, GetMyReservationsResponses, GetReservationByIdData, GetReservationByIdResponses, GetReservationsData, GetReservationsResponses, GetUserEventsData, GetUserEventsResponses, GetUserTicketsData, GetUserTicketsResponses, HealthControllerLiveData, HealthControllerLiveResponses, HealthControllerReadyData, HealthControllerReadyResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutErrors, LogoutResponses, RegisterData, RegisterErrors, RegisterResponses, ReserveEventData, ReserveEventResponses, UpdateEventData, UpdateEventResponses, UpdateReservationData, UpdateReservationResponses } from './types.gen';
import { zCancelReservationData, zCreateEventData, zCreateEventResponse, zDeleteEventData, zDeleteEventResponse, zDeleteReservationData, zDeleteReservationResponse, zFindUserByIdData, zFindUserByIdResponse, zGetCurrentUserData, zGetCurrentUserResponse, zGetEventByIdData, zGetEventByIdResponse, zGetEventReservationsData, zGetEventReservationsResponse, zGetEventsData, zGetEventsResponse, zGetMyEventsData, zGetMyEventsResponse, zGetMyReservationsData, zGetMyReservationsResponse, zGetReservationByIdData, zGetReservationByIdResponse, zGetReservationsData, zGetReservationsResponse, zGetUserEventsData, zGetUserEventsResponse, zGetUserTicketsData, zGetUserTicketsResponse, zHealthControllerLiveData, zHealthControllerReadyData, zLoginData, zLoginResponse, zLogoutData, zRegisterData, zRegisterResponse, zReserveEventData, zReserveEventResponse, zUpdateEventData, zUpdateEventResponse, zUpdateReservationData, zUpdateReservationResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Liveness check
 */
export const healthControllerLive = <ThrowOnError extends boolean = false>(options?: Options<HealthControllerLiveData, ThrowOnError>) => (options?.client ?? client).get<HealthControllerLiveResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHealthControllerLiveData.parseAsync(data),
    url: '/health/live',
    ...options
});

/**
 * Readiness check
 */
export const healthControllerReady = <ThrowOnError extends boolean = false>(options?: Options<HealthControllerReadyData, ThrowOnError>) => (options?.client ?? client).get<HealthControllerReadyResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHealthControllerReadyData.parseAsync(data),
    url: '/health/ready',
    ...options
});

/**
 * Get paged and searchable events
 */
export const getEvents = <ThrowOnError extends boolean = false>(options?: Options<GetEventsData, ThrowOnError>) => (options?.client ?? client).get<GetEventsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetEventsData.parseAsync(data),
    responseTransformer: getEventsResponseTransformer,
    responseValidator: async (data) => await zGetEventsResponse.parseAsync(data),
    url: '/events',
    ...options
});

/**
 * Create event
 */
export const createEvent = <ThrowOnError extends boolean = false>(options: Options<CreateEventData, ThrowOnError>) => (options.client ?? client).post<CreateEventResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zCreateEventData.parseAsync(data),
    responseTransformer: createEventResponseTransformer,
    responseValidator: async (data) => await zCreateEventResponse.parseAsync(data),
    url: '/events',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get current user events
 */
export const getMyEvents = <ThrowOnError extends boolean = false>(options?: Options<GetMyEventsData, ThrowOnError>) => (options?.client ?? client).get<GetMyEventsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetMyEventsData.parseAsync(data),
    responseTransformer: getMyEventsResponseTransformer,
    responseValidator: async (data) => await zGetMyEventsResponse.parseAsync(data),
    url: '/events/me',
    ...options
});

/**
 * Delete event
 */
export const deleteEvent = <ThrowOnError extends boolean = false>(options: Options<DeleteEventData, ThrowOnError>) => (options.client ?? client).delete<DeleteEventResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDeleteEventData.parseAsync(data),
    responseValidator: async (data) => await zDeleteEventResponse.parseAsync(data),
    url: '/events/{id}',
    ...options
});

/**
 * Get event by id
 */
export const getEventById = <ThrowOnError extends boolean = false>(options: Options<GetEventByIdData, ThrowOnError>) => (options.client ?? client).get<GetEventByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetEventByIdData.parseAsync(data),
    responseTransformer: getEventByIdResponseTransformer,
    responseValidator: async (data) => await zGetEventByIdResponse.parseAsync(data),
    url: '/events/{id}',
    ...options
});

/**
 * Update event
 */
export const updateEvent = <ThrowOnError extends boolean = false>(options: Options<UpdateEventData, ThrowOnError>) => (options.client ?? client).put<UpdateEventResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zUpdateEventData.parseAsync(data),
    responseTransformer: updateEventResponseTransformer,
    responseValidator: async (data) => await zUpdateEventResponse.parseAsync(data),
    url: '/events/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get event reservations
 */
export const getEventReservations = <ThrowOnError extends boolean = false>(options: Options<GetEventReservationsData, ThrowOnError>) => (options.client ?? client).get<GetEventReservationsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetEventReservationsData.parseAsync(data),
    responseTransformer: getEventReservationsResponseTransformer,
    responseValidator: async (data) => await zGetEventReservationsResponse.parseAsync(data),
    url: '/events/{id}/reservations',
    ...options
});

/**
 * Get current authenticated user
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>) => (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetCurrentUserData.parseAsync(data),
    responseTransformer: getCurrentUserResponseTransformer,
    responseValidator: async (data) => await zGetCurrentUserResponse.parseAsync(data),
    url: '/users/me',
    ...options
});

/**
 * Find user by ID
 */
export const findUserById = <ThrowOnError extends boolean = false>(options: Options<FindUserByIdData, ThrowOnError>) => (options.client ?? client).get<FindUserByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zFindUserByIdData.parseAsync(data),
    responseTransformer: findUserByIdResponseTransformer,
    responseValidator: async (data) => await zFindUserByIdResponse.parseAsync(data),
    url: '/users/{id}',
    ...options
});

/**
 * Get user tickets
 */
export const getUserTickets = <ThrowOnError extends boolean = false>(options: Options<GetUserTicketsData, ThrowOnError>) => (options.client ?? client).get<GetUserTicketsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetUserTicketsData.parseAsync(data),
    responseTransformer: getUserTicketsResponseTransformer,
    responseValidator: async (data) => await zGetUserTicketsResponse.parseAsync(data),
    url: '/users/{id}/ticket',
    ...options
});

/**
 * Get user events
 */
export const getUserEvents = <ThrowOnError extends boolean = false>(options: Options<GetUserEventsData, ThrowOnError>) => (options.client ?? client).get<GetUserEventsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetUserEventsData.parseAsync(data),
    responseTransformer: getUserEventsResponseTransformer,
    responseValidator: async (data) => await zGetUserEventsResponse.parseAsync(data),
    url: '/users/{id}/events',
    ...options
});

/**
 * Get paginated reservations
 */
export const getReservations = <ThrowOnError extends boolean = false>(options?: Options<GetReservationsData, ThrowOnError>) => (options?.client ?? client).get<GetReservationsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetReservationsData.parseAsync(data),
    responseTransformer: getReservationsResponseTransformer,
    responseValidator: async (data) => await zGetReservationsResponse.parseAsync(data),
    url: '/reservations',
    ...options
});

/**
 * Reserve an event
 */
export const reserveEvent = <ThrowOnError extends boolean = false>(options: Options<ReserveEventData, ThrowOnError>) => (options.client ?? client).post<ReserveEventResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zReserveEventData.parseAsync(data),
    responseTransformer: reserveEventResponseTransformer,
    responseValidator: async (data) => await zReserveEventResponse.parseAsync(data),
    url: '/reservations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get my reservations
 */
export const getMyReservations = <ThrowOnError extends boolean = false>(options?: Options<GetMyReservationsData, ThrowOnError>) => (options?.client ?? client).get<GetMyReservationsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetMyReservationsData.parseAsync(data),
    responseTransformer: getMyReservationsResponseTransformer,
    responseValidator: async (data) => await zGetMyReservationsResponse.parseAsync(data),
    url: '/reservations/me',
    ...options
});

/**
 * Delete a reservation
 */
export const deleteReservation = <ThrowOnError extends boolean = false>(options: Options<DeleteReservationData, ThrowOnError>) => (options.client ?? client).delete<DeleteReservationResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDeleteReservationData.parseAsync(data),
    responseValidator: async (data) => await zDeleteReservationResponse.parseAsync(data),
    url: '/reservations/{id}',
    ...options
});

/**
 * Get reservation by ID
 */
export const getReservationById = <ThrowOnError extends boolean = false>(options: Options<GetReservationByIdData, ThrowOnError>) => (options.client ?? client).get<GetReservationByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetReservationByIdData.parseAsync(data),
    responseTransformer: getReservationByIdResponseTransformer,
    responseValidator: async (data) => await zGetReservationByIdResponse.parseAsync(data),
    url: '/reservations/{id}',
    ...options
});

/**
 * Update a reservation
 */
export const updateReservation = <ThrowOnError extends boolean = false>(options: Options<UpdateReservationData, ThrowOnError>) => (options.client ?? client).patch<UpdateReservationResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zUpdateReservationData.parseAsync(data),
    responseTransformer: updateReservationResponseTransformer,
    responseValidator: async (data) => await zUpdateReservationResponse.parseAsync(data),
    url: '/reservations/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Cancel a reservation
 */
export const cancelReservation = <ThrowOnError extends boolean = false>(options: Options<CancelReservationData, ThrowOnError>) => (options.client ?? client).post<CancelReservationResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zCancelReservationData.parseAsync(data),
    url: '/reservations/{id}/cancel',
    ...options
});

/**
 * Login user
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    requestValidator: async (data) => await zLoginData.parseAsync(data),
    responseTransformer: loginResponseTransformer,
    responseValidator: async (data) => await zLoginResponse.parseAsync(data),
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register new user
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    requestValidator: async (data) => await zRegisterData.parseAsync(data),
    responseTransformer: registerResponseTransformer,
    responseValidator: async (data) => await zRegisterResponse.parseAsync(data),
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout user
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    requestValidator: async (data) => await zLogoutData.parseAsync(data),
    url: '/auth/logout',
    ...options
});
