// This file is auto-generated by @hey-api/openapi-ts

import type { CreateEventResponse, FindUserByIdResponse, GetCurrentUserResponse, GetEventByIdResponse, GetEventReservationsResponse, GetEventsResponse, GetMyEventsResponse, GetMyReservationsResponse, GetReservationByIdResponse, GetReservationsResponse, GetUserEventsResponse, GetUserTicketsResponse, LoginResponse, RegisterResponse, ReserveEventResponse, UpdateEventResponse, UpdateReservationResponse } from './types.gen';

const eventDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

const pagedEventsDtoSchemaResponseTransformer = (data: any) => {
    data.events = data.events.map((item: any) => eventDtoSchemaResponseTransformer(item));
    return data;
};

export const getEventsResponseTransformer = async (data: any): Promise<GetEventsResponse> => {
    data = pagedEventsDtoSchemaResponseTransformer(data);
    return data;
};

export const createEventResponseTransformer = async (data: any): Promise<CreateEventResponse> => {
    data = eventDtoSchemaResponseTransformer(data);
    return data;
};

export const getMyEventsResponseTransformer = async (data: any): Promise<GetMyEventsResponse> => {
    data = pagedEventsDtoSchemaResponseTransformer(data);
    return data;
};

export const getEventByIdResponseTransformer = async (data: any): Promise<GetEventByIdResponse> => {
    data = eventDtoSchemaResponseTransformer(data);
    return data;
};

export const updateEventResponseTransformer = async (data: any): Promise<UpdateEventResponse> => {
    data = eventDtoSchemaResponseTransformer(data);
    return data;
};

const userDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

const reservationDtoSchemaResponseTransformer = (data: any) => {
    data.purchasedAt = new Date(data.purchasedAt);
    data.event = eventDtoSchemaResponseTransformer(data.event);
    if (data.user) {
        data.user = userDtoSchemaResponseTransformer(data.user);
    }
    return data;
};

export const getEventReservationsResponseTransformer = async (data: any): Promise<GetEventReservationsResponse> => {
    data = data.map((item: any) => reservationDtoSchemaResponseTransformer(item));
    return data;
};

export const getCurrentUserResponseTransformer = async (data: any): Promise<GetCurrentUserResponse> => {
    data = userDtoSchemaResponseTransformer(data);
    return data;
};

export const findUserByIdResponseTransformer = async (data: any): Promise<FindUserByIdResponse> => {
    data = userDtoSchemaResponseTransformer(data);
    return data;
};

export const getUserTicketsResponseTransformer = async (data: any): Promise<GetUserTicketsResponse> => {
    data = data.map((item: any) => reservationDtoSchemaResponseTransformer(item));
    return data;
};

export const getUserEventsResponseTransformer = async (data: any): Promise<GetUserEventsResponse> => {
    data = pagedEventsDtoSchemaResponseTransformer(data);
    return data;
};

const pagedReservationsDtoSchemaResponseTransformer = (data: any) => {
    data.reservations = data.reservations.map((item: any) => reservationDtoSchemaResponseTransformer(item));
    return data;
};

export const getReservationsResponseTransformer = async (data: any): Promise<GetReservationsResponse> => {
    data = pagedReservationsDtoSchemaResponseTransformer(data);
    return data;
};

export const reserveEventResponseTransformer = async (data: any): Promise<ReserveEventResponse> => {
    data = reservationDtoSchemaResponseTransformer(data);
    return data;
};

export const getMyReservationsResponseTransformer = async (data: any): Promise<GetMyReservationsResponse> => {
    data = data.map((item: any) => reservationDtoSchemaResponseTransformer(item));
    return data;
};

export const getReservationByIdResponseTransformer = async (data: any): Promise<GetReservationByIdResponse> => {
    data = reservationDtoSchemaResponseTransformer(data);
    return data;
};

export const updateReservationResponseTransformer = async (data: any): Promise<UpdateReservationResponse> => {
    data = reservationDtoSchemaResponseTransformer(data);
    return data;
};

const authResponseDtoSchemaResponseTransformer = (data: any) => {
    data.user = userDtoSchemaResponseTransformer(data.user);
    return data;
};

export const loginResponseTransformer = async (data: any): Promise<LoginResponse> => {
    data = authResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const registerResponseTransformer = async (data: any): Promise<RegisterResponse> => {
    data = authResponseDtoSchemaResponseTransformer(data);
    return data;
};
