// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CreateEventDto = {
    title: string;
    location?: string;
    startsAt: Date;
    price: number;
};

export type EventDto = {
    id: number;
    title: string;
    location?: string | null;
    startsAt: string;
    price: number;
    organizerId: number;
    createdAt: Date;
};

export type PagedEventsDto = {
    events: Array<EventDto>;
    total: number;
    page: number;
    limit: number;
    totalPages: number;
};

export type UserDto = {
    id: number;
    email: string;
    role: 'user' | 'admin';
    createdAt: Date;
};

export type ReservationDto = {
    id: number;
    userId: number;
    eventId: number;
    status: 'reserved' | 'paid' | 'cancelled';
    purchasedAt: Date;
    event: EventDto;
    user?: UserDto;
};

export type UpdateEventDto = {
    title?: string;
    location?: string | null;
    startsAt?: Date;
    price?: number;
};

export type PagedUsersDto = {
    users: Array<UserDto>;
    total: number;
    page: number;
    limit: number;
    totalPages: number;
};

export type UpdateUserDto = {
    email?: string;
    role?: 'user' | 'admin';
};

export type PagedReservationsDto = {
    reservations: Array<ReservationDto>;
    total: number;
    page: number;
    limit: number;
    totalPages: number;
};

export type ReserveEventDto = {
    eventId: number;
    status: 'paid' | 'reserved';
};

export type UpdateReservationDto = {
    eventId?: number;
    status?: 'paid' | 'reserved';
};

export type LoginDto = {
    email: string;
    password: string;
};

export type AuthResponseDto = {
    user: UserDto;
};

export type RegisterDto = {
    email: string;
    password: string;
};

export type HealthControllerLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type HealthControllerLiveResponses = {
    200: unknown;
};

export type HealthControllerReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type HealthControllerReadyResponses = {
    200: unknown;
};

export type GetEventsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/events';
};

export type GetEventsResponses = {
    200: PagedEventsDto;
};

export type GetEventsResponse = GetEventsResponses[keyof GetEventsResponses];

export type CreateEventData = {
    body: CreateEventDto;
    path?: never;
    query?: never;
    url: '/events';
};

export type CreateEventResponses = {
    201: EventDto;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type GetMyEventsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/events/me';
};

export type GetMyEventsResponses = {
    200: PagedEventsDto;
};

export type GetMyEventsResponse = GetMyEventsResponses[keyof GetMyEventsResponses];

export type DeleteEventData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type DeleteEventResponses = {
    204: void;
};

export type DeleteEventResponse = DeleteEventResponses[keyof DeleteEventResponses];

export type GetEventByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type GetEventByIdResponses = {
    200: EventDto;
};

export type GetEventByIdResponse = GetEventByIdResponses[keyof GetEventByIdResponses];

export type UpdateEventData = {
    body: UpdateEventDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type UpdateEventResponses = {
    200: EventDto;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type GetEventReservationsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}/reservations';
};

export type GetEventReservationsResponses = {
    200: Array<ReservationDto>;
};

export type GetEventReservationsResponse = GetEventReservationsResponses[keyof GetEventReservationsResponses];

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/users';
};

export type GetAllUsersResponses = {
    200: PagedUsersDto;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetCurrentUserResponses = {
    200: UserDto;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type DeleteUserResponses = {
    /**
     * User deleted successfully
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type FindUserByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type FindUserByIdResponses = {
    200: UserDto;
};

export type FindUserByIdResponse = FindUserByIdResponses[keyof FindUserByIdResponses];

export type UpdateUserData = {
    body: UpdateUserDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type UpdateUserResponses = {
    200: UserDto;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type GetUserTicketsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}/ticket';
};

export type GetUserTicketsResponses = {
    200: Array<ReservationDto>;
};

export type GetUserTicketsResponse = GetUserTicketsResponses[keyof GetUserTicketsResponses];

export type GetUserEventsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/users/{id}/events';
};

export type GetUserEventsResponses = {
    200: PagedEventsDto;
};

export type GetUserEventsResponse = GetUserEventsResponses[keyof GetUserEventsResponses];

export type GetReservationsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/reservations';
};

export type GetReservationsResponses = {
    200: PagedReservationsDto;
};

export type GetReservationsResponse = GetReservationsResponses[keyof GetReservationsResponses];

export type ReserveEventData = {
    body: ReserveEventDto;
    path?: never;
    query?: never;
    url: '/reservations';
};

export type ReserveEventResponses = {
    201: ReservationDto;
};

export type ReserveEventResponse = ReserveEventResponses[keyof ReserveEventResponses];

export type GetMyReservationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reservations/me';
};

export type GetMyReservationsResponses = {
    200: Array<ReservationDto>;
};

export type GetMyReservationsResponse = GetMyReservationsResponses[keyof GetMyReservationsResponses];

export type DeleteReservationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/reservations/{id}';
};

export type DeleteReservationResponses = {
    204: void;
};

export type DeleteReservationResponse = DeleteReservationResponses[keyof DeleteReservationResponses];

export type GetReservationByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/reservations/{id}';
};

export type GetReservationByIdResponses = {
    200: ReservationDto;
};

export type GetReservationByIdResponse = GetReservationByIdResponses[keyof GetReservationByIdResponses];

export type UpdateReservationData = {
    body: UpdateReservationDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/reservations/{id}';
};

export type UpdateReservationResponses = {
    200: ReservationDto;
};

export type UpdateReservationResponse = UpdateReservationResponses[keyof UpdateReservationResponses];

export type CancelReservationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/reservations/{id}/cancel';
};

export type CancelReservationResponses = {
    200: unknown;
};

export type LoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type LoginResponses = {
    200: AuthResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * User with this email already exists
     */
    409: unknown;
};

export type RegisterResponses = {
    201: AuthResponseDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type LogoutResponses = {
    /**
     * Successfully logged out
     */
    200: unknown;
};
