// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCreateEventDto = z.object({
    title: z.string().min(1).max(100),
    location: z.optional(z.string().max(255)),
    startsAt: z.iso.date().regex(/^\d{4}-\d{2}-\d{2}$/),
    price: z.number().gte(0).lte(1000000)
});

export const zEventDto = z.object({
    id: z.number(),
    title: z.string(),
    location: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    startsAt: z.string(),
    price: z.number(),
    organizerId: z.number(),
    createdAt: z.iso.datetime()
});

export const zPagedEventsDto = z.object({
    events: z.array(zEventDto),
    total: z.number(),
    page: z.number(),
    limit: z.number(),
    totalPages: z.number()
});

export const zUserDto = z.object({
    id: z.number(),
    email: z.string(),
    role: z.enum([
        'guest',
        'user',
        'admin'
    ]),
    createdAt: z.iso.datetime()
});

export const zReservationDto = z.object({
    id: z.number(),
    userId: z.number(),
    eventId: z.number(),
    status: z.enum([
        'reserved',
        'paid',
        'cancelled'
    ]),
    purchasedAt: z.iso.datetime(),
    event: zEventDto,
    user: z.optional(zUserDto)
});

export const zUpdateEventDto = z.object({
    title: z.optional(z.string().min(1).max(100)),
    location: z.optional(z.union([
        z.string().max(255),
        z.null()
    ])),
    startsAt: z.optional(z.iso.date().regex(/^\d{4}-\d{2}-\d{2}$/)),
    price: z.optional(z.number().gte(0).lte(1000000))
});

export const zPagedReservationsDto = z.object({
    reservations: z.array(zReservationDto),
    total: z.number(),
    page: z.number(),
    limit: z.number(),
    totalPages: z.number()
});

export const zReserveEventDto = z.object({
    eventId: z.number().gte(1),
    status: z.enum(['paid', 'reserved'])
});

export const zUpdateReservationDto = z.object({
    eventId: z.optional(z.number().gte(1)),
    status: z.optional(z.enum(['paid', 'reserved']))
});

export const zLoginDto = z.object({
    email: z.email().max(255),
    password: z.string().min(6).max(100)
});

export const zAuthResponseDto = z.object({
    user: zUserDto
});

export const zRegisterDto = z.object({
    email: z.email().max(255),
    password: z.string().min(6).max(100)
});

export const zHealthControllerLiveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zHealthControllerReadyData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetEventsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.number().gte(1)).default(1),
        limit: z.optional(z.number().gte(1).lte(100)).default(10)
    }))
});

export const zGetEventsResponse = zPagedEventsDto;

export const zCreateEventData = z.object({
    body: zCreateEventDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zCreateEventResponse = zEventDto;

export const zGetMyEventsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.number().gte(1)).default(1),
        limit: z.optional(z.number().gte(1).lte(100)).default(10)
    }))
});

export const zGetMyEventsResponse = zPagedEventsDto;

export const zDeleteEventData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.number()
    }),
    query: z.optional(z.never())
});

export const zDeleteEventResponse = z.void();

export const zGetEventByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.number()
    }),
    query: z.optional(z.never())
});

export const zGetEventByIdResponse = zEventDto;

export const zUpdateEventData = z.object({
    body: zUpdateEventDto,
    path: z.object({
        id: z.number()
    }),
    query: z.optional(z.never())
});

export const zUpdateEventResponse = zEventDto;

export const zGetEventReservationsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.number()
    }),
    query: z.optional(z.never())
});

export const zGetEventReservationsResponse = z.array(zReservationDto);

export const zGetCurrentUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetCurrentUserResponse = zUserDto;

export const zFindUserByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.number()
    }),
    query: z.optional(z.never())
});

export const zFindUserByIdResponse = zUserDto;

export const zGetUserTicketsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.number()
    }),
    query: z.optional(z.never())
});

export const zGetUserTicketsResponse = z.array(zReservationDto);

export const zGetUserEventsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.number()
    }),
    query: z.optional(z.object({
        page: z.optional(z.number().gte(1)).default(1),
        limit: z.optional(z.number().gte(1).lte(100)).default(10)
    }))
});

export const zGetUserEventsResponse = zPagedEventsDto;

export const zGetReservationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.number().gte(1)).default(1),
        limit: z.optional(z.number().gte(1).lte(100)).default(10)
    }))
});

export const zGetReservationsResponse = zPagedReservationsDto;

export const zReserveEventData = z.object({
    body: zReserveEventDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zReserveEventResponse = zReservationDto;

export const zGetMyReservationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetMyReservationsResponse = z.array(zReservationDto);

export const zDeleteReservationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.number()
    }),
    query: z.optional(z.never())
});

export const zDeleteReservationResponse = z.void();

export const zGetReservationByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.number()
    }),
    query: z.optional(z.never())
});

export const zGetReservationByIdResponse = zReservationDto;

export const zUpdateReservationData = z.object({
    body: zUpdateReservationDto,
    path: z.object({
        id: z.number()
    }),
    query: z.optional(z.never())
});

export const zUpdateReservationResponse = zReservationDto;

export const zCancelReservationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.number()
    }),
    query: z.optional(z.never())
});

export const zLoginData = z.object({
    body: zLoginDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zLoginResponse = zAuthResponseDto;

export const zRegisterData = z.object({
    body: zRegisterDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zRegisterResponse = zAuthResponseDto;

export const zLogoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});
