/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as ReservationsIndexRouteImport } from './routes/reservations/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as ReservationsReservationIdRouteImport } from './routes/reservations/$reservationId'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIndexRoute = ReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsReservationIdRoute =
  ReservationsReservationIdRouteImport.update({
    id: '/reservations/$reservationId',
    path: '/reservations/$reservationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/reservations/$reservationId': typeof ReservationsReservationIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/events': typeof EventsIndexRoute
  '/reservations': typeof ReservationsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/reservations/$reservationId': typeof ReservationsReservationIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/events': typeof EventsIndexRoute
  '/reservations': typeof ReservationsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/reservations/$reservationId': typeof ReservationsReservationIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/events/': typeof EventsIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$eventId'
    | '/reservations/$reservationId'
    | '/users/$userId'
    | '/events'
    | '/reservations'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/$eventId'
    | '/reservations/$reservationId'
    | '/users/$userId'
    | '/events'
    | '/reservations'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/events/$eventId'
    | '/reservations/$reservationId'
    | '/users/$userId'
    | '/events/'
    | '/reservations/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  ReservationsReservationIdRoute: typeof ReservationsReservationIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ReservationsIndexRoute: typeof ReservationsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/': {
      id: '/reservations/'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/$reservationId': {
      id: '/reservations/$reservationId'
      path: '/reservations/$reservationId'
      fullPath: '/reservations/$reservationId'
      preLoaderRoute: typeof ReservationsReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  ReservationsReservationIdRoute: ReservationsReservationIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  ReservationsIndexRoute: ReservationsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
