Enum user_role {
  guest
  user
  organizer
  admin
}

Enum attendance_status {
  reserved
  paid
  cancelled
}

Table user {
  id int [pk, increment]
  email varchar [unique, not null]
  password_hash varchar [not null]
  full_name varchar
  role user_role [not null]
  created_at datetime
}

Table event {
  id int [pk, increment]
  title varchar [not null]
  description text
  location varchar
  start_time datetime [not null]
  end_time datetime [not null]
  organizer_id int [not null]
  created_at datetime
}

Table ticket {
  id int [pk, increment]
  event_id int [not null]
  name varchar [not null]   
  price decimal [not null]
}

Table user_ticket {
  id int [pk, increment]
  user_id int [not null]
  ticket_id int [not null]

  purchase_date datetime [not null]
  status attendance_status [not null]
}

Table reviews {
  id int [pk, increment]
  event_id int [not null]
  user_id int [not null]
  rating int [not null]       
  comment text
  created_at datetime
}

Ref: event.organizer_id > user.id
Ref: ticket.event_id > event.id
Ref: user_ticket.user_id > user.id
Ref: user_ticket.ticket_id > ticket.id
Ref: reviews.event_id > event.id
Ref: reviews.user_id > user.id
